### ISSUE TITLE
SN candidate: remove alerts with ndethist=1

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-filters#48]
They are probably SSO... (I can see they are very correlated):

<img width="593" alt="Screenshot 2021-05-28 at 11 34 57" src="https://user-images.githubusercontent.com/20426972/119963752-c080a780-bfa8-11eb-98d2-417272668814.png">

@anaismoller

**Comment by JulienPeloton** [comment]
At least, we can remove alerts that have a counterpart in MPC!

**Comment by anaismoller** [comment]
Can you give a little bit of context?
